import React from 'react'
import { ScrollView, View, Text, TouchableOpacity } from 'react-native'
import CustomModal from '../../../components/CustomModal'
import { modalStyle } from '../../../styles/LoginPageStyles'
import { LanguageModalStyles, LocationModalStyles } from '../../../styles/RegisterStyle'
import { countries } from '../../../utils/constants'

type Props = {
    setIsOpen: React.Dispatch<React.SetStateAction<boolean>>
    setSelectedHospital:  React.Dispatch<React.SetStateAction<string>>
    selectedHospital ?: string,
    isOpen: boolean
}


const HospitalsModal = ({isOpen,setIsOpen, setSelectedHospital, selectedHospital}: Props) => {

const content =    <View style={LocationModalStyles.container}>
    <Text style={modalStyle.modalTitleStyle}>
        Select Hospital
    </Text>
    <ScrollView style={[LanguageModalStyles.languagesList,{height: 400}]}>
                            {Hospitals.map((element,index) => (
                              <TouchableOpacity key={index} onPress={()=>{
                                setSelectedHospital(element);
                                setIsOpen(false)
                                }}>
                                <Text style={element === selectedHospital ? LocationModalStyles.highlightedText : {color: "#fff", fontFamily: 'Lora-Bold'}}>{element}</Text>
                              </TouchableOpacity>
                            ))}
        </ScrollView>
    </View>

  return (
    <CustomModal content={content} onBackdropPress={()=>setIsOpen(false)} visible={isOpen} />
  )
}

export default HospitalsModal


const Hospitals = [
    'Arnavutköy Devlet Hastanesi',
    'Başakşehir Devlet Hastanesi',
    'Bahçelievler Devlet Hastanesi',
    'Bayrampaşa Devlet Hastanesi',
    'Beykoz Devlet Hastanesi',
    'Beşiktaş Sait Çiftçi Devlet Hastanesi',
    'Büyükçekmece Mimar Sinan Devlet Hastanesi',
    'Çatalca İlyas Çokay Devlet Hastanesi',
    'Esenyurt Necmi Kadıoğlu Devlet Hastanesi',
    'Eyüpsultan Devlet Hastanesi',
    'İstinye Devlet Hastanesi',
   'Kağıthane Devlet Hastanesi',
    'Maltepe Devlet Hastanesi',
    'Pendik Devlet Hastanesi',
    'Tuzla Devlet Hastanesi',
    'Silivri Devlet Hastanesi',
    'Esenler Kadın Doğum ve Çocuk Hastalıkları Hastanesi',
    'Sultanbeyli Devlet Hastanesi',
    'Şile Devlet Hastanesi',
    'Üsküdar Devlet Hastanesi',
    'Academic Hospital, Altunizade',
    'Adatıp Hastanesi, Kurtköy',
    'Aile Hastanesi, Bahçelievler',
   'Acıbadem Hastanesi, Bakırköy',
    'Acıbadem Hastanesi, Fulya',
   'Acıbadem Hastanesi, Kadıköy',
    'Acıbadem Hastanesi, Kozyatağı',
    'Acıbadem Hastanesi, Maslak',
    'Acıbadem Hastanesi, Taksim',
    'Elitium Hastanesi, Avcılar 7',
   'Acıbadem International Hospital, Yeşilköy',
    'Akça Hastanesi, Fatih',
    'Aksaray Vatan Hastanesi',
   'Aksoy Hastanesi, Şişli',
    'Alman Hastanesi, Taksim',
   'Amerikan Hastanesi (American Hospital), Nişantaşı',
    'Anadolu Hastanesi, Üsküdar',
    'Ataköy Hastanesi, Yenibosna',
    'Avcılar Anadolu Hastanesi',
    'Avcılar Candan Hastanesi',
    'Avcılar Hayat Hastanesi',
    'Avcılar Hospital',
    'Avicenna Hastanesi, Esenler',
   'Avrasya Hospital, Sultangazi',
   'Avrasya Hospital, Zeytinburnu',
    'Avrupa Hastanesi, Mecidiyeköy',
    'Avrupa Cerrahi, Bakırköy',
    'Avusturya Saint George Hastanesi, Karaköy',
    'Özel Bağcılar Hastanesi',
    'Bahat Hospital Sultangazi',
   'Bahçelievler Ömür Hastanesi',
    'Bakırköy Ömür Hastanesi',
    'Balat Or-Ahayim Musevi Hastanesi, Fatih',
    'Balıklı Rum Hastanesi, Zeytinburnu',
    'Balkan Hastanesi, Bahçelievler',
    'Bayındır Hastanesi İçerenköy, Ataşehir',
    'Bayrampaşa Göz Hastanesi, Eyüpsultan',
    'Beşyüzevler Hayat Hastanesi, Bayrampaşa',
   'Birincigöz Hastanesi, Beylikdüzü',
   'Birinci Hastanesi, Beylikdüzü',
    'Bilge Hastanesi, Gaziosmanpaşa',
   'Bilgi Hastanesi, Şişli',
    'Büyük Anadolu Hastanesi, Şirinevler',
   'Özel Büyükçekmece Hastanesi',
   'Can Hastanesi, Şişli',
    'Central Hospital, Kozyatağı',
   'Çağıner Hastanesi, Kadıköy',
    'Çamlıca Hayat Hastanesi',
   'Çamlıca Ömür Hastanesi',
    'Çamlık Hastanesi',
    'Çapa Hastanesi',
    'Çapa Millet Hastanesi',
    'Çevre Hastanesi, Mecidiyeköy',
    'DentGroup Diş Hastanesi, Acarkent',
    'DentGroup Diş Hastanesi, Ataşehir',
   'DentGroup Diş Hastanesi, Bağdat Caddesi',
   'DentGroup Diş Hastanesi, Bahçelievler',
    'DentGroup Diş Hastanesi, Çekmeköy',
    'DentGroup Diş Hastanesi, Göztepe',
    'DentGroup Kids Diş Hastanesi, Caddebostan',
   'DentGroup Diş Hastanesi, Maltepe',
   'DentGroup Diş Hastanesi, Maslak',
    'DentGroup Diş Hastanesi, Nişantaşı',
   'DentGroup Diş Hastanesi, Yenibosna',
   'Diyabet Hastanesi, Şişli',
   'Dora Hospital, Kağıthane',
   'Doğan Hastanesi, Küçükçekmece',
   'Doğaner Hastanesi, Fatih',
   'Dragos Hastanesi',
   'Dragos Şifa Hastanesi',
   'Dünya Göz Hastanesi, 1. Levent',
   'Düzey Göz Merkezi - Avcılar',
   'Erdem Hastanesi, Ümraniye',
   'Eren Hastanesi, Ataşehir',
   'Esnaf Hastanesi, Eminönü',
   'Fatih Hastanesi',
   'Fatih Tıp Merkezi',
   'Ferihan Laçin Hastanesi',
   'Fertijin Kadın Hastalıkları ve Doğum Merkezi, Nişantaşı',
    'Florence Nightingale Avrupa Hastanesi, Şişli',
   'Florence Nightingale Hastanesi, Çağlayan',
    'Florence Nightingale Metropolitan Hastanesi, Gayrettepe',
    'Özel Gaziosmanpaşa Hastanesi',
    'Gelişim Hastanesi, Bahçelievler',
   'Göksoy Hastanesi, Kadıköy',
    'Göz Nurunu Koruma Vakfı Bayrampaşa Göz Hastanesi',
   'Göz Sağlığı Merkezi',
    'Güzelbahçe Hastanesi, Nişantaşı',
    'Halkalı Kent Hastanesi',
    'Hattat Hastanesi, 3. Levent',
    'Hospitadent Diş Hastanesi, Bakırköy',
    'Hospitadent Diş Hastanesi, Fatih',
   'Hospitadent Diş Hastanesi, Mecidiyeköy',
    'Hospitadent Diş Hastanesi, Çamlıca',
    'Hospitadent Diş Hastanesi, Pendik',
    'Hospitadent Diş Hastanesi, Bağcılar',
   'Hospitalist Hastanesi',
   'Haznedar Hastanesi, Bahçelievler',
   'Haznedar Ömür Hastanesi',
   'Hisar Intercontinental Hospital, Ümraniye',
   'Hisar Hospital, Çamlıca',
   'Hizmet Hastanesi, Bahçelievler',
   'Huzur Hastanesi, Fatih',
   'İncirli Hastanesi, Bakırköy',
   'İstanbul Diş Hastanesi, Şişli',
   'Özel İstanbul Hospital, İkitelli',
   'İtalyan Hastanesi, Tophane',
   'Ota-Jinemed Hospital, Beşiktaş',
  'John F. Kennedy Hospital, Bahçelievler',
  'Kadıköy Şifa Hastanesi',
  'Kadıköy Vatan Hastanesi',
    'Kadıoğlu Hastanesi, Mecidiyeköy',
   'Kolan Hastanesi, Şişli',
    'Kolan Hastanesi, Beylikdüzü',
   'Lape Hastanesi, Şişli',
   'Levent Hastanesi, 4. Levent',
   'Lifemed Tıp Merkezi, Kadıköy',
   'Liv Hospital , Ulus',
   'Marmara Hastanesi, Maltepe',
   'Medicalist Cerrahi Tıp Merkezi',
   'Medicana Beylikdüzü Hastanesi',
   'Medicana Bahçelievler Hastanesi',
   'Medicine Hospital , Esenyurt',
   'Medilife Hastanesi, Beylikdüzü',
   'Medilife Hastanesi, Bağcılar',
   'Medilife Hastanesi, Çapa',
   'Medipol Hastanesi, Koşuyolu',
   'Medipol Mega Hastanesi Bağcılar',
   'Medipol Hastanesi Bahçelievler',
  'Medipol Hastanesi Sefaköy',
   'Medipol Hastanesi Pendik',
   'Medipol Hastanesi Çamlıca',
   'Medistate Hastanesi',
   'Megadent Ağız ve Diş Sağlığı Kurumları',
   'Memorial Hastanesi , Şişli',
   'Merter Vatan Hastanesi',
   'Meyan Hastanesi, Kozyatağı',
   'Nisa Hastanesi , Yenibosna',
   'NPİSTANBUL Nöropsikiyatri Hastanesi, Ümraniye',
   'Özel Okmeydanı Hastanesi',
  'Ortadoğu Hastanesi, Kartal',
   'Özel Göztepe Hastanesi',
   'Özel İkitelli Bahat Hastanesi',
   'Özel Kartal Hospital, Kartal',
   'Özel Kurtköy Tıp Merkezi',
   'Özel Prodenta Diş Hastanesi',
   'Özel Umut Hastanesi',
   'Safa Hastanesi Yenibosna',
   'Sanita Diş Hastanesi',
   'Saygı Hastanesi',
   'Sema Hastanesi',
  'Seyfi Basa Çocuk Hastanesi, Kadıköy',
   'Surp Agop Hastanesi, Şişli',
   'Surp Pırgiç Ermeni Hastanesi , Kazlıçeşme',
  'Şafak Hastanesi, Gaziosmanpaşa',
   'Tekden Özel Hastane , İkitelli',
   'Tem Hospital, İkitelli',
    'Tepebaşı Vatan Hastanesi',
   'Tosunoğlu Hastanesi, Şenesenevler',
   'Türkiye Gazetesi Hastanesi, Şişli',
    'Üsküdar Hastanesi',
   'Vatan Hastanesi, Aksaray',
   'Yaşar Hastanesi, Bakırköy',
   'Yeni Bosna Hastanesi',
   'Yeni Ufuk Hastanesi',
   'Yeşil Bahar Hastanesi, Çiftehavuzlar',
   'Yunus Emre Hastanesi',
   'ERKA Hastanesi , Gaziosmanpaşa',
   'Asya Hastanesi, Gaziosmanpaşa',
]