export { default as userController } from './user.controller';
export { default as authController } from './auth.controller';
export { default as blogController } from './blog.controller';
export { default as foodRecognitionController } from './foodRecognition.controller';
export { default as appointmentController } from './appointment.controller';
export { default as medecineImageController } from './medecineImage.controller';
export { default as categoryController } from './category.controller';
export { default as productController } from './product.controller';
export { default as orderController } from './order.controller';
