export const AUTH_TOKEN = 'auth-token';
export const partners = ['Partner XYZ 1',
    'Partner XYZ 2',
    'Partner XYZ 3',
    'Partner XYZ 4',
    'Partner XYZ 5',
    'Partner XYZ 6',
    'Partner XYZ 7',
    'Partner XYZ 8',
    'Partner XYZ 9',
    'Partner XYZ 10',
    'Partner XYZ 11',
    'Partner XYZ 12',
    'Partner XYZ 13',
    'Partner XYZ 14',
    'Partner XYZ 15',
    'Partner XYZ 16',
    'Partner XYZ 17',
    'Partner XYZ 18',
    'Partner XYZ 19',
    'Partner XYZ 20',
    'Partner XYZ 21',
    'Partner XYZ 22',
    'Partner XYZ 23',
    'Partner XYZ 24',
    'Partner XYZ 25',
    'Partner XYZ 26',
    'Partner XYZ 27',
    'Partner XYZ 28',
    'Partner XYZ 29',
    'Partner XYZ 30'
]

export const employers = ['Employer XYZ 1',
    'Employer XYZ 2',
    'Employer XYZ 3',
    'Employer XYZ 4',
    'Employer XYZ 5',
    'Employer XYZ 6',
    'Employer XYZ 7',
    'Employer XYZ 8',
    'Employer XYZ 9',
    'Employer XYZ 10',
    'Employer XYZ 11',
    'Employer XYZ 12',
    'Employer XYZ 13',
    'Employer XYZ 14',
    'Employer XYZ 15',
    'Employer XYZ 16',
    'Employer XYZ 17',
    'Employer XYZ 18',
    'Employer XYZ 19',
    'Employer XYZ 20',
    'Employer XYZ 21',
    'Employer XYZ 22',
    'Employer XYZ 23',
    'Employer XYZ 24',
    'Employer XYZ 25',
    'Employer XYZ 26',
    'Employer XYZ 27',
    'Employer XYZ 28',
    'Employer XYZ 29',
    'Employer XYZ 30'
]

export const countries = ["United States", "Canada", "Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and/or Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Cook Islands", "Costa Rica", "Croatia (Hrvatska)", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "France, Metropolitan", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard and Mc Donald Islands", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan", "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia South Sandwich Islands", "Spain", "Sri Lanka", "St. Helena", "St. Pierre and Miquelon", "Sudan", "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic", "Taiwan", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States minor outlying islands", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City State", "Venezuela", "Vietnam", "Virgin Islands (British)", "Virgin Islands (U.S.)", "Wallis and Futuna Islands", "Western Sahara", "Yemen", "Yugoslavia", "Zaire", "Zambia", "Zimbabwe"]

export const languages = ['Romani',
    'Romanin',
    'Russian',
    'Rwanda',
    'Samoan',
    'SanSkrit',
    'Serbian',
    'Shona',
    'Sindhi',
    'Sinhala',
    'Slovak',
    'Slovene',
    'Somali',
    'Spanish',
    'Swahili',
    'Swedish',
    'Tachelhit',
    'Tagalog',
    'Tajiki',
    'Tamil',
    'Tatar',
    'Telugu',
    'Thai',
    'Tibetic',
    'Tigrigna',
    'Tok',
    'Pisin',
    'Turkish',
    'Turkmen',
    'Ukrainian',
    'Urdu',
    'Uyghur',
    'Uzbek',
    'Vietnamese',
    'Warlpiri',
    'Welsh',
    'Wolof',
    'Xhosa',
    'Yakut',
    'Yiddish',
    'Yoruba',
    'Yucatec',
    'Zapotec',
    'Zulu',
    'Afrikaans',
    'Albanian',
    'Amharic',
    'Arabic',
    'Aramaic',
    'Armenian',
    'Assamese',
    'Aymara',
    'Azerbaijani',
    'Balochi',
    'Bamanankan Bashkort', 
    'Basque',
    'Belarusan',
    'Bengali',
    'Bhojpuri',
    'Bislama',
    'Bosnian',
    'Brahui',
    'Bulgarian',
    'Burmese',
    'Cantonese',
    'Catalan',
    'Cebuano',
    'Chechen',
    'Cherokee',
    'Croatian',
    'Czech',
    'Dakota',
    'Danish',
    'Dari',
    'Dholuo',
    'Dutch',
    'English',
    'Esperanto',
    'Estonian',
    'Éwé',
    'Finnish',
    'French',
    'Georgian',
    'German',
    'Gikuyu',
    'Greek',
    'Guarani',
    'Gujarati',
    'Haitian',
    'Creole',
    'Hausa',
    'Hawaiian',
    'Hebrew',
    'Hiligaynon',
    'Hindi',
    'Hungarian',
    'Icelandic',
    'Igbo',
    'Ilocano',
    'Indonesian',
    'Inuit/Inupiaq',
    'Irish',
    'Gaelic',
    'Italian',
    'Japanese',
    'Jarai',
    'Javanese',
    'K’iche’',
    'Kabyle',
    'Kannada',
    'Kashmiri',
    'Kazakh',
    'Khmer',
    'Khoe',
    'khoe',
    'Korean',
    'Kurdish',
    'Kyrgyz',
    'Lao',
    'Latin',
    'Latvian',
    'Lingala',
    'Lithuanian',
    'Macedonian',
    'Maithili',
    'Malagasy',
    'Malay',
    'Malayalam',
    'Mandarin',
    'Marathi',
    'Mende',
    'Mongolian',
    'Nahuatl',
    'Navajo',
    'Nepali',
    'Norwegian',
    'Ojibwa',
    'Oriya',
    'Oromo',
    'Pashto',
    'Persian',
    'Polish',
    'Portuguese',
    'Punjabi',
    'Quechua']