export const SET_LOGIN_METHOD_PHONE_NUMBER = 'SET_LOGIN_METHOD_PHONE_NUMBER';
export const SET_LOGIN_METHOD_EMAIL = 'SET_LOGIN_METHOD_EMAIL';
export const OPEN_PICTURE_PICKER_MODAL = 'OPEN_PICTURE_PICKER_MODAL';
export const CLOSE_PICTURE_PICKER_MODAL = 'CLOSE_PICTURE_PICKER_MODAL';
export const OPEN_MEMBERSHIP_MODAL = 'OPEN_MEMBERSHIP_MODAL';
export const CLOSE_MEMBERSHIP_MODAL = 'CLOSE_MEMBERSHIP_MODAL';
export const SET_USER_PICTURE = 'SET_USER_PICTURE';
