import {Dimensions, StyleSheet} from 'react-native';
import { colors } from '../variables/colors';
export const PADDING_HORIZONTAL = 20;
export const MARGIN_DOT = 5;
export const DOT_SIZE = 8;
const styles = StyleSheet.create({
  Container: {
    backgroundColor: colors.backgroundColor,
    paddingTop: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Header: {
    display: 'flex',
    alignItems: 'flex-end',
    width: '100%',
    paddingHorizontal: 20,
  },
  HeaderGroup: {
    width: '75%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  HeaderGroupInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    paddingHorizontal: 5,
  },
  SkipButton: {
    fontFamily: 'Roboto',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: -0.23999999463558197,
    color: '#414042',
    opacity: 0.5,
  },
  homepageContainer: {
    height: '100%',
  },
  IllustrationContainer: {
    height: '40%',
    flexDirection: 'row',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  Illustration: {
    resizeMode: 'stretch',
    width: Dimensions.get('screen').width * 0.65,
    height: 170,
  },
  HeaderLogo: {
    resizeMode: 'contain',
  },
  ScrollView: {
    height: '100%',
  },
  ScrollViewElement: {
    flex: 0.9,
    width: Dimensions.get('screen').width,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'column',
    paddingVertical: 25,
    paddingHorizontal: PADDING_HORIZONTAL,
    backgroundColor: '#fff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  FlatListTitle: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 22,
    width: 220,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 31,
    letterSpacing: -0.23999999463558197,
    textAlign: 'center',
    color: '#414042',
  },
  FlatListDesc: {
    fontFamily: 'Lora-Regular',
    fontSize: 14,
    width: 300,
    fontStyle: 'normal',
    fontWeight: '300',
    lineHeight: 20,
    letterSpacing: -0.23999999463558197,
    textAlign: 'center',
    color: '#414042',
  },
  FlatListNextButton: {
    width: 300,
    height: 47,
    backgroundColor: colors.MedixBotPrimaryColor,
    borderRadius: 30,
    justifyContent: 'center',
  },
  NextButtonText: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 20,
    letterSpacing: 0.23999999463558197,
    textAlign: 'center',
    color: '#fff',
  },
  GradientNext: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
    justifyContent: 'center',
  },
  ReadMoreButton: {
    width: 100,
    height: 30,
    borderRadius: 25,
    borderColor: colors.MedixBotPrimaryColor,
    borderWidth: 1,
    justifyContent: 'center',
  },
  ReadMoreButtonText: {
    fontFamily: 'Montserrat-SemiBold',
    color: colors.MedixBotPrimaryColor,
    textAlign: 'center',
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 5,
    backgroundColor: '#414042',
    opacity: 0.2,
    marginLeft: 5,
  },
  dotIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.MedixBotPrimaryColor,
    marginLeft: 5,
  },
  dotIndicatorGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
    backgroundColor: colors.MedixBotPrimaryColor,
  },
  dotContainer: {flexDirection: 'row', alignItems: 'center'},
  infoPage: {
    backgroundColor: '#fff',
    borderTopRightRadius: 40,
    borderTopLeftRadius: 40,
    height: '90%',
    marginTop: '8%',
    width: '100%',
    paddingHorizontal: 25,
    paddingVertical: 50,
  },
  infoPageTitle: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 25,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 25,
    letterSpacing: -0.23999999463558197,
    textAlign: 'left',
    color: '#000',
  },
  infoPageDesc: {
    fontFamily: 'Lora-Regular',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 16,
    letterSpacing: -0.23999999463558197,
    textAlign: 'left',
    color: '#000000C9',
    paddingVertical: 14,
  },
});
export default styles;
