name: Deploy to dev environment

env:
  APP_NAME: medixbot-api
  AWS_ACCESS_KEY_ID: AKIAR6C3ZIK35S3WFGCG
  AWS_SECRET_ACCESS_KEY: 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
  ENVIRONMENT_NAME: Medixbotapi-env-1

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build:api
      - run: npm run copy

      - name: Generate deployment package
        run: zip -r deploy.zip ./apps/api/dist/. -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APP_NAME }}
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          version_label: 12345
          use_existing_version_if_available: true
          region: eu-central-1
          deployment_package: deploy.zip
