name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/medixbot . -f Dockerfile.dev

      - name: Push Docker image to DockerHub
        run: |
          echo ${{secrets.DOCKER_HUB_TOKEN_MEDIXBOT}} | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/medixbot

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          username: ${{secrets.DROPLET_USER}}

          script: |
            docker stop medixbot-container || true
            docker pull ${{secrets.DOCKER_HUB_USERNAME}}/medixbot
            docker run -d --rm --name medixbot-container -p 4000:4000 ${{secrets.DOCKER_HUB_USERNAME}}/medixbot
